### ISSUE TITLE
Add Variant of Concern Omnikron (B.1.1.529) to website

### ISSUE THREAD

**Issue by EwoutH** [cov-lineages/lineages-website#12]
SARS-CoV-2 Variant B.1.1.529 was indicated as a Variant of Concern by the WHO last Friday. Could it be added to the cov-linages website? (https://cov-lineages.org/index.html#global_reports)

WHO: [Classification of Omicron (B.1.1.529): SARS-CoV-2 Variant of Concern](https://www.who.int/news/item/26-11-2021-classification-of-omicron-(b.1.1.529)-sars-cov-2-variant-of-concern)

**Comment by aineniamh** [comment]
It's on the to-do list! In the meantime, we have the lineage page here: https://cov-lineages.org/lineage.html?lineage=B.1.1.529

**Comment by aineniamh** [comment]
It's up now and should hopefully be auto-updating from tomorrow!

**Comment by EwoutH** [comment]
Awesome, thanks for the very quick implementation!
