### ISSUE TITLE
Placement of BB.2 in lineage_list.html

### ISSUE THREAD

**Issue by jknappen** [cov-lineages/lineages-website#17]
It is inconsistently placed after the BA.* lineages and not below B.1.621.1.

**Comment by jknappen** [comment]
It still displaced in the current build of the website. Besides that, the withdrawn lineage BB.1 is missing completely (it was assigned here https://github.com/cov-lineages/pango-designation/issues/232 and later re-absorbed in B.1.621.1)

**Comment by rmcolq** [comment]
Closing as stale
