### ISSUE TITLE
Summary of Currently Defined Constellations table not shown

### ISSUE THREAD

**Issue by ljr080808** [cov-lineages/lineages-website#2]
Hello! I realized that the table of Summary of Currently Defined Constellations cannot be properly shown in the webpage (https://cov-lineages.org/constellations.html). Perhaps there's any error?
![Constellations](https://user-images.githubusercontent.com/40150825/125048695-c5ba3180-e0d2-11eb-926b-6e0c11830341.png)

**Comment by rkdover** [comment]
![image](https://user-images.githubusercontent.com/54945737/125954509-824cde86-129a-4a62-aa19-48c634989796.png)
Loads for me, but it is a bit delayed from the page itself loading.

**Comment by ljr080808** [comment]
> ![image](https://user-images.githubusercontent.com/54945737/125954509-824cde86-129a-4a62-aa19-48c634989796.png)
> Loads for me, but it is a bit delayed from the page itself loading.

**Comment by ljr080808** [comment]
> ![image](https://user-images.githubusercontent.com/54945737/125954509-824cde86-129a-4a62-aa19-48c634989796.png)
> Loads for me, but it is a bit delayed from the page itself loading.

I have checked again, is it still not shown even I tried different browser.

**Comment by emilyscher** [comment]
Do you see anything in your browser’s javascript console?

**Comment by rkdover** [comment]
I just tried to load the page with severe network throttling (1kbps) and get the described behaviour. The page takes a while to load, shows the surrounding web page, and then takes quite long to load the list itself. What kind of connection are you on?

**Comment by rmcolq** [comment]
Closing as stale
