### ISSUE TITLE
https://cov-lineages.org/lineage_list.html --> no lineages displayed

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/lineages-website#22]
Hi there,

is this issue connected to one of the others, listed here?
I do not see any lineages listed.

![image](https://user-images.githubusercontent.com/23099946/200811469-4e07bc09-7edb-40de-b655-ceb99eeb3b19.png)

Greets

**Comment by rmcolq** [comment]
Yes, same issue - I'm working on a fix

**Comment by AKWB** [comment]
would it be possible to provide a simple tsv-file (as in early days) with the same data normally displayed on the webpage? This would at least allow us to continue annotation of lineages in our reporting.

**Comment by rmcolq** [comment]
The information that is loaded into that table is available in JSON format here https://github.com/cov-lineages/lineages-website/blob/master/_data/lineage_data.json (or if that file is too large for you, the same info is currently spread equally into 5 files with the names https://github.com/cov-lineages/lineages-website/blob/master/_data/lineage_data_X.json). Feel free to parse them instead

**Comment by AKWB** [comment]
For those who might need it as well:

import pandas as pd

pdObj = pd.read_json('lineage_data.json', orient='index')
pdObj.to_csv('lineageData.csv', columns=["Lineage","Countries","Earliest date","Number designated","Number Assigned","Description"], index=False)

**Comment by rmcolq** [comment]
OK, this page is now live again although it has now been filtered to only those lineages which have been seen globally in the last year.

Note for future me: 
- git-lfs doesn't support github-pages
- tried chunking up the JSON. This might work with better javascript, but in my test case did not.

**Comment by AKWB** [comment]
do you have somewhere still the BIG json file? As we are reprocessing all our samples with anew pangolin update, including all lineages...I think I saw somewhere a file > 100MB (?)

**Comment by aineniamh** [comment]
We could theoretically push the large file to git-lfs and provide a link to the website, even if it won't be able to be rendered on the website

**Comment by rmcolq** [comment]
The original file has been pushed back to the LFS `https://github.com/cov-lineages/lineages-website/blob/master/_data/lineage_data.full.json`
