### ISSUE TITLE
Missing name for B.1.1.529

### ISSUE THREAD

**Issue by abel-betraoui** [cov-lineages/lineages-website#26]
I might be missing something here, so please excuse me if this issue is irrelevant.

I noticed the B.1.1.529 variant "node" is missing from the lineages.yml meaning contrary to other variants, there is no name field associated with B.1.1.529. It does show up as a parent of the BA.1 variant though.

It was not the case up until commit 1570749 [before](https://github.com/cov-lineages/lineages-website/blob/bc0cdc9d0d917f26b67f1153d4441b4d9803d6c3/data/lineages.yml) / [after](https://github.com/cov-lineages/lineages-website/blob/1570749f5db45141200d57a111e845658a459ae5/data/lineages.yml)
Is this intentional ?

Cheers

**Comment by rmcolq** [comment]
The lineages.yml no longer displays lineages which have not been seen in the last year because the file size had got too large. B.1.1.529 doesn't get assigned, so will not have had any sequences. Might be worth keeping as an exception though

**Comment by abel-betraoui** [comment]
Thanks for the quick answer. For what it's worth, it would help us quite a lot to have it as an exception.

**Comment by rmcolq** [comment]
Should hopefully appear back as soon as the page is redeployed
