### ISSUE TITLE
lineages assigned but not annotated in the json file (or online) 

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/lineages-website#28]
Hi there,

I just ran an analysis and came across a case of BQ.1.13.1. This lineage is not to find in the annotation-json file.
--> looks like this is solved.

I am still missing XBB.1.9 (?)

Greets

**Comment by aineniamh** [comment]
This lineage was only added after the last pangolin-data release (https://github.com/cov-lineages/pango-designation/blame/04cb7e2da40144f0ad33510a0addb2290dfffc6e/lineage_notes.txt#L2395) so has not been incorporated into the latest model yet, so hasn't appeared on the website. The next pangolin-data release should include this lineage.
