### ISSUE TITLE
lineage_data_full.json up to date?

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/lineages-website#29]
Hi there, 

I am missing basically several lineages in this file: 
e.g.
EE.4
EF.2

last update was on the 28/01, but the latest data rather end of Feb.

Greets

**Comment by rmcolq** [comment]
Hi @AKWB, the server that was running the updates had a major failure recently and it's taking us time to get it back live. In the mean time there is some help here https://github.com/cov-lineages/lineages-website/issues/27 for possible workarounds to get similar information

**Comment by AKWB** [comment]
Any update on this? besides the workaround...

**Comment by rmcolq** [comment]
Website should receive an update when the pipeline finishes probably late tomorrow

**Comment by AKWB** [comment]
Hi there,
Are you still updating the file lineage_data_full.json?
I saw it was moved to _data. We are using it for annotation purposes.
Best

**Comment by AKWB** [comment]
or, do I switch to this? Is this uptodate?
https://raw.githubusercontent.com/cov-lineages/pango-designation/master/lineage_notes.txt

**Comment by AngieHinrichs** [comment]
> https://raw.githubusercontent.com/cov-lineages/pango-designation/master/lineage_notes.txt

Yes, that file is up to date.  Depending on your needs, you might also find https://raw.githubusercontent.com/cov-lineages/pango-designation/master/pango_designation/alias_key.json useful and @corneliusroemer's python package [pango_aliasor](https://github.com/corneliusroemer/pango_aliasor) that uses alias_key.json to expand and contract lineage aliases.
