### ISSUE TITLE
pango.network link to lineages list is broken

### ISSUE THREAD

**Issue by rkdover** [cov-lineages/lineages-website#3]
As I understand it pango.network is also managed by this team. In any case I did not find another repository or contact details. Remove the issue if this isn't correct.

Link at https://www.pango.network/the-pango-nomenclature-system/list-of-designated-lineages/ is broken. It is currently https://cov-lineages.org/lineages.html while the correct URL is https://cov-lineages.org/lineage_list.html.

**Comment by aineniamh** [comment]
Ah great thanks, I've updated that link now- should work once the update takes!
