### ISSUE TITLE
./lineages.html not redirecting to ./lineages-list.html?

### ISSUE THREAD

**Issue by rambaut** [cov-lineages/lineages-website#4]
Just gives blank page (Safari).

**Comment by rambaut** [comment]
Redirects correctly on Chrome

**Comment by rkdover** [comment]
Is this related to #3? I also don't get a redirect on Edge. Blank page and nothing in console.

**Comment by emilyscher** [comment]
Have just pushed a fix, should be in effect soon. It seems that we somehow wound up with both a lineaeges.html and a lineages.md, removing one did the trick.
